name:
hosts: all // this means give access to all servers in hosts file
remote_user:
role: 

//handlers
- name: updated.html copy
  template: 
  notify:
    - Restart Nginx
    //update nginx when html got updated

//variables in ansible
vars:
  //string
  main_var: "foo"
  //boolean
  is_enebled: false
  //list
  fruits:
    - mango
    - apple
  //dictionary variables
  price_fruits:
    - mango: 2.50
    - apple: 3.11